registries:
  - type: standard
    ref: v4.235.0

packages:
  - name: cli/cli@v2.74.0
  - name: dandavison/delta@0.18.2
  - name: mikefarah/yq@v4.45.4
  - name: gitleaks/gitleaks@v8.24.3
  - name: aquasecurity/trivy@v0.62.1
  - name: anchore/syft@v1.26.1
  - name: anchore/grype@v0.92.0
  - name: sigstore/cosign@v2.5.0
  - name: hadolint/hadolint@v2.12.0
